### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Thefunkymunkee** [eracknaphobia/plugin.video.nbcsnliveextra-legacy#1]
Hi I've got it installed on my xbmc. 13.2 Gotham. But I can't play anything live. I'm in the UK. Do I need a VPN or subscription to this for it to play live??

**Comment by eracknaphobia** [comment]
Check out the forum. Post #30 might be what you are looking for.

http://forum.xbmc.org/showthread.php?tid=171476 http://forum.xbmc.org/showthread.php?tid=171476&page=2 &page=2
