### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by membranaraptor** [eracknaphobia/plugin.video.nbcsnliveextra-legacy#13]
My NBC add on has not been working for the past two weeks. It will only open up the free streams, not the premium, despite the fact that it was working perfectly before. I've tried different servers on my VPN, tried different VPNs, uninstalled and reinstalled, and updated but it still returns with a "script failed" error. I have been unable to get a log as this also returns a script failed error (these are the only two apps that have done this). Is there any way to fix this as I use this add on more than any other. Thanks in advance.

**Comment by eracknaphobia** [comment]
If the log program is getting script errors you may have network configuration issues that go beyond the scope of this addon.

You can manually get the log files
