### ISSUE TITLE
Premium Content Dummy

### ISSUE THREAD

**Issue by random-robbie** [eracknaphobia/plugin.video.nbcsnliveextra-legacy#14]
Hi,

When using a smart dns provider some of the akamaihd links work (not just NBC sports and NBC golf)

are you able to add a provider called SMART DNS so that if you use a smart dns service the premium links become active?

**Comment by eracknaphobia** [comment]
Nope, you still need a cable / satellite subscription no matter if you use vpn or dns proxies. Please use the forum for any future questions.

http://forum.kodi.tv/showthread.php?tid=207159
