### ISSUE TITLE
streams drop after 2 minutes

### ISSUE THREAD

**Issue by ralyodio** [eracknaphobia/plugin.video.nbcsnliveextra-legacy#16]
tried several live streams and they always drop after about 2 minutes. Happens repeatedly.
other streams on other plugins work fine. it happens on both osx and firetv/kodi

I'm using v2015.11.12

Here is my log.

http://xbmclogs.com/porfpt7lh

**Comment by eracknaphobia** [comment]
I noticed that too on my fire tv. Not sure why windows kodi is not affected by it. Possibly a kodi / ffmpeg bug?

**Comment by ralyodio** [comment]
i see it on both mac (15.2), linux (15.2) and firetv (14.2). If I had to hazard a guess I would say its due to the token re-authorization request if that happens every 2 minutes. That could be failing causing the stream to not be authenticated and drop

**Comment by joshplatt94** [comment]
Any chance we can code in Hotwire if I provide my login details for NBC

Sent from myMail for iOS

Tuesday, 17 November 2015, 20:10 +0000 from notifications@github.com notifications@github.com:

I noticed that too on my fire tv. Not sure why windows kodi is not affected by it. Possibly a kodi / ffmpeg bug?

**Comment by ralyodio** [comment]
@joshplatt94 hotwire? I can send you an invite to screenhero. Just give me your email.

**Comment by joshplatt94** [comment]
Yes hotwire communications they do are company that provide broadband and cable to big communities. My email is jplatty23@hotmail.com

Sent from myMail for iOS

Wednesday, 18 November 2015, 01:14 +0000 from notifications@github.com notifications@github.com:

@joshplatt94https://github.com/joshplatt94 hotwire? I can send you an invite to screenhero. Just give me your email.

**Comment by ralyodio** [comment]
@joshplatt94 invite sent.

**Comment by joshplatt94** [comment]
I have received it, we can do it later today. I am currently in London but just tell me what time works for you

Sent from myMail for iOS

Wednesday, 18 November 2015, 05:31 +0000 from notifications@github.com notifications@github.com:

@joshplatt94https://github.com/joshplatt94 invite sent.

**Comment by ralyodio** [comment]
@eracknaphobia any luck with this?

You could install Ubuntu on virtualbox vm and test it. I think its a simple bug as I've never ran into an issue where streams don't work cross platform.

**Comment by mameha** [comment]
Any update on this?

I am having this issue on Kodi 15.2 running on android 4.2.2, latest NBC addon version.

**Comment by eracknaphobia** [comment]
Try the latest release (2015.12.29) it should fix the issue with live streams dropping.
