### ISSUE TITLE
Kodi

### ISSUE THREAD

**Issue by random-robbie** [eracknaphobia/plugin.video.nbcsnliveextra-legacy#2]
Hi 

whats needed to update the plugin to work in kodi i am currently stuck on a nightly due to mac osx problems and when i try run the addon its complaining of incorrect addon structure.

Keep up the good work!

**Comment by eracknaphobia** [comment]
I’m not sure what the issue would be. I’m running the add-on on the lastest kodi alpha release on a pc and it seems to be fine. I’ll see what I can find out but you might try posting the question to the forum and see if anyone else has an idea.

http://forum.xbmc.org/showthread.php?tid=171476

**Comment by random-robbie** [comment]
ignore me it worked when i extracted it in to the plugins folder it appeared no addon would work.

think it was due to the nightly having issues.

Sorry!

**Comment by eracknaphobia** [comment]
No problem. Glad it's working for you.
