### ISSUE TITLE
No Valid Football Links

### ISSUE THREAD

**Issue by ian10951** [eracknaphobia/plugin.video.nbcsnliveextra-legacy#25]
The Football Links are no longer contained in the json so the addon cannot find them and therefore they cannot turn blue to be able to play them.

The only way I know of finding the Links and cookie is by using Wireshark, they could be hiding in plain site disguised as something else,but I cannot see them.

So the addon needs re coding to enable python to find them.

**Comment by ralyodio** [comment]
I think you mean soccer? (j/k)

**Comment by ian10951** [comment]
Its called Football in England, but yes if your American its the Soccer url's.

**Comment by twenty3thirty0** [comment]
How about crowd sourcing the links from pastebin or something similar. 
Similar to how some of the IPTV setups work.

For example, 
- add a new setting to specify a pastbin link
- decode URLS for matches from the pastebin either via a new menu option (e.g. Custom links) or by replacing unmatched links from the Live & Upcoming feed

This may not be ideal, and might only need to be a work around for now, but I'm sure the community would appreciate it.

**Comment by twenty3thirty0** [comment]
@eracknaphobia I've made my above change for allowing custom links to be decoded from a pastbin. Works well with non-football feeds so far. will need to wait until saturday's games to trial against the EPL feeds. i can push the changes to the repo if you provide access, or i can simply send to you in an zip. let me know.

I'm going to look into methods of scraping the feeds direct. will keep you posted

**Comment by eracknaphobia** [comment]
no crowd sourcing.
